const data = {
  products: [
    {
      //_id: '1',
      name: 'Handmade Lamp',
      slug: 'indoor-lamp',
      category: 'lamp',
      image: '/images/indoor-lamp.jpg',
      price: 100,
      countInStock: 10,
      brand: 'local',
      rating: 4.5,
      numReviews: 1,
      description: 'High quality indoor lamp',
    },

    {
      //_id: '2',
      name: 'Handmade Bag',
      slug: 'printed-bag',
      category: 'bag',
      image: '/images/printed-bag.jpg',
      price: 300,
      countInStock: 10,
      brand: 'local',
      rating: 4.5,
      numReviews: 12,
      description: 'High quality handbag',
    },

    {
      //_id: '3',
      name: 'Handmade teacup',
      slug: 'teacup-set',
      category: 'kitchen',
      image: '/images/tea-cup-set.jpg',
      price: 120,
      countInStock: 15,
      brand: 'local',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality tea cup set',
    },

    {
      //_id: '4',
      name: 'Homdecor',
      slug: 'decor-set',
      category: 'decoration',
      image: '/images/home-decor.jpg',
      price: '200',
      countInStock: '10',
      brand: 'local',
      rating: 4.5,
      numReviews: 1,
      description: 'High quality decoration item',
    },
    {
      //_id: '4',
      name: 'Homdecor item',
      slug: 'decorset',
      category: 'decoration',
      image: '/images/homedecor.jpg',
      price: '200',
      countInStock: '10',
      brand: 'local',
      rating: 4.5,
      numReviews: 1,
      description: 'High quality decoration item',
    },
  ],
};

export default data;
